### PR TITLE
Add missing pikmins

### PR DESCRIPTION
**Pull request by danmichaelo**
This PR adds the

* tiny book pikmins #8 
* train station ticket pikmins #9 
* mountain and weather pikmins #10 
* special chess piece pikmins #11 

and renames "mini mart" to "corner store"

Btw. let me know if you need a new maintainer, I can probably help out.

---

Update: I've also experimented a little bit with making the app a PWA: https://github.com/danmichaelo/pikmin-bloom-checklist/commit/7adfed786b8e6c72b569e615dfd3b2438d18d8a8 – seems to work pretty well, the app loads faster and doesn't reload each time I open it.

### CODE REVIEW

**Comment by Notuom** [comment]
Thanks for the contribution! I'll try and get this reviewed soon - I haven't had much free time recently and haven't kept up with the game since I stopped playing a while ago.

For the PWA part, feel free to open another PR, totally open to it if it doesn't break anything!

**Comment by danmichaelo** [comment]
Understand that! Would you be interested in either transferring ownership of the project or add me as maintainer? I'm actively playing the game and also work with NextJS in my daytime job

**Comment by Notuom** [comment]
> Understand that! Would you be interested in either transferring ownership of the project or add me as maintainer? I'm actively playing the game and also work with NextJS in my daytime job

Sure, I can add you as a maintainer, thanks! So far I'd been using conventional commits, semver and a changelog but it's a bit overkill for a project like this, so feel free to proceed without all that. I have a quick and dirty deploy npm script which should work as long as you have push access.

**Review by Notuom — APPROVED** [review]

**Comment by Notuom** [comment]
One call-out: changing the order of things currently breaks sharing because of how the encoding is done, so this constant will need to be bumped so as to not send erroneous data, but I doubt a lot of people would encounter this edge case anyways.

https://github.com/Notuom/pikmin-bloom-checklist/blob/main/utils/encoding.ts#L20-L24

**Comment by Notuom** [comment]
fixes #8, fixes #9, fixes #10, fixes #11

**Comment by danmichaelo** [comment]
> One call-out: changing the order of things in the decors list currently breaks sharing because of how the encoding is done, so this constant will need to be bumped so as to not send erroneous data, but I doubt a lot of people would encounter this edge case anyways.
> 
> https://github.com/Notuom/pikmin-bloom-checklist/blob/main/utils/encoding.ts#L20-L24
> 
> I'll merge this PR and bump up this constant for now.

Thanks! And good to know! Moving forward, I'll probably continue to do PRs for updates, inviting you to review them if you have time, but don't feel any pressure to do so.

**Pull request merged**
